title: Introduction To Data Science
description: Introduction To Data Science Course By Vishal Kamalakrishnan
theme: just-the-docs

url: https://thev123.github.io/intro-to-data-science/

aux_links:
  Template Repository: https://github.com/TheV123/intro-to-data-science

relative_permalinks: false